import 'package:flutter/material.dart';

class LocalizationProvider with ChangeNotifier {
  Locale _currentLocale = const Locale('hy');

  Locale get currentLocale => _currentLocale;

  static final Map<String, Map<String, String>> _localizedValues = {
    'hy': {
      'appName': 'DigiCraft-ի առաքում',
      'searchHint': 'Որոնման հարթակ՝ ընտրեք ձեր սրտի նախընտրելին ',
      'categoriesTitle': 'Ցանկ',
      'popularRestaurants': 'Հայտնի Ռեստորաններ',
      'noResults': 'Որոնման արդյունքում ոչինչ չի գտնվել',
      'login': 'Մուտք',
      'register': 'Գրանցում',
      'welcome': 'Բարի գալուստ DigiCraft առաքում',
      'usernameOrEmail': 'Մուտքանուն կամ Էլ. հասցե',
      'password': 'Գաղտնաբառ',
      'name': 'Անուն Ազգանուն',
      'username': 'Մուտքանուն',
      'email': 'Էլ. հասցե',
      'confirmPassword': 'Կրկնել Գաղտնաբառը',
      'noAccount': 'Չունե՞ք հաշիվ: Գրանցվեք այստեղ',
      'requiredField': 'Պարտադիր դաշտ',
      'invalidEmail': 'Մուտքագրեք ճիշտ էլ. հասցե',
      'shortPassword': 'Գաղտնաբառը պետք է լինի առնվազն 6 նիշ',
      'passwordMismatch': 'Գաղտնաբառերը չեն համընկնում',
      'registrationSuccess': 'Գրանցումը հաջողվեց։ Այժմ կարող եք մուտք գործել։',
      'cartTitle': 'Ձեր Զամբյուղը',
      'emptyCart': 'Ձեր զամբյուղը դատարկ է',
      'total': 'Ընդհանուր',
      'checkout': 'Ձևակերպել պատվերը',
      'orderSuccess': 'Պատվերը ընդունված է:',
      'orderMessage': 'Ձեր համեղ ուտեստը արդեն ճանապարհին է:',
      'addedToCart': 'Ավելացված է Ձեր Զամբյուղում',
      'catAll': 'Ամբողջը',
      'catPizza': 'Պիցցա',
      'catBurger': 'Բուրգեր',
      'catSushi': 'Սուշի',
      'catPasta': 'Պաստա',
      'catDessert': 'Աղանդեր',
    },
    'en': {
      'appName': 'DigiCraft Delivery',
      'searchHint': 'Search here, pick your favorite',
      'categoriesTitle': 'Menu',
      'popularRestaurants': 'Popular Restaurants',
      'noResults': 'No results found',
      'login': 'Login',
      'register': 'Register',
      'welcome': 'Welcome to DigiCraft Delivery',
      'usernameOrEmail': 'Username or Email',
      'password': 'Password',
      'name': 'Full Name',
      'username': 'Username',
      'email': 'Email',
      'confirmPassword': 'Confirm Password',
      'noAccount': "Don't have an account? Register here",
      'requiredField': 'Required field',
      'invalidEmail': 'Enter a valid email',
      'shortPassword': 'Password must be at least 6 characters',
      'passwordMismatch': 'Passwords do not match',
      'registrationSuccess': 'Registration successful. You can now login.',
      'cartTitle': 'Your Cart',
      'emptyCart': 'Your cart is empty',
      'total': 'Total',
      'checkout': 'Checkout',
      'orderSuccess': 'Order Accepted!',
      'orderMessage': 'Your delicious meal is on its way!',
      'addedToCart': 'Added to your cart',
      'catAll': 'All',
      'catPizza': 'Pizza',
      'catBurger': 'Burger',
      'catSushi': 'Sushi',
      'catPasta': 'Pasta',
      'catDessert': 'Dessert',
    },
    'ru': {
      'appName': 'DigiCraft Доставка',
      'searchHint': 'Ищите здесь, выбирайте любимое',
      'categoriesTitle': 'Меню',
      'popularRestaurants': 'Популярные рестораны',
      'noResults': 'Ничего не найдено',
      'login': 'Вход',
      'register': 'Регистрация',
      'welcome': 'Добро пожаловать в DigiCraft Доставка',
      'usernameOrEmail': 'Имя пользователя или Email',
      'password': 'Пароль',
      'name': 'Имя Фамилия',
      'username': 'Имя пользователя',
      'email': 'Электронная почта',
      'confirmPassword': 'Подтвердите пароль',
      'noAccount': 'Нет аккаунта? Зарегистрируйтесь здесь',
      'requiredField': 'Обязательное поле',
      'invalidEmail': 'Введите корректный email',
      'shortPassword': 'Пароль должен быть не менее 6 символов',
      'passwordMismatch': 'Пароли не совпадают',
      'registrationSuccess': 'Регистрация прошла успешно. Теперь вы можете войти.',
      'cartTitle': 'Ваша корзина',
      'emptyCart': 'Ваша корзина пуста',
      'total': 'Итог',
      'checkout': 'Оформить заказ',
      'orderSuccess': 'Заказ принят!',
      'orderMessage': 'Ваша вкусная еда уже в пути!',
      'addedToCart': 'Добавлено в корзину',
      'catAll': 'Все',
      'catPizza': 'Пицца',
      'catBurger': 'Бургер',
      'catSushi': 'Суши',
      'catPasta': 'Паста',
      'catDessert': 'Десерт',
    },
  };

  void setLocale(Locale locale) {
    if (!['hy', 'en', 'ru'].contains(locale.languageCode)) return;
    _currentLocale = locale;
    notifyListeners();
  }

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }
}
