import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationProvider with ChangeNotifier {
  Locale _currentLocale = const Locale('hy');
  static const String _localeKey = 'selected_locale';

  Locale get currentLocale => _currentLocale;

  LocalizationProvider() {
    loadLocale();
  }

  Future<void> loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString(_localeKey);
    if (savedCode != null && ['hy', 'en', 'ru'].contains(savedCode)) {
      _currentLocale = Locale(savedCode);
      notifyListeners();
    }
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'hy': {
      'appName': 'MASOOR',
      'searchHint': 'Որոնման հարթակ՝ ընտրեք ձեր սրտի նախընտրելին ',
      'categoriesTitle': 'Ցանկ',
      'popularRestaurants': 'Հայտնի Ռեստորաններ',
      'noResults': 'Որոնման արդյունքում ոչինչ չի գտնվել',
      'login': 'Մուտք',
      'register': 'Գրանցում',
      'welcome': 'Բարի գալուստ MASOOR',
      'usernameOrEmail': 'Օգտանուն',
      'password': 'Գաղտնաբառ',
      'name': 'Անուն',
      'username': 'Օգտանուն',
      'email': 'Էլեկտրոնային փոստ',
      'confirmPassword': 'Կրկնել Գաղտնաբառը',
      'noAccount': 'Չունե՞ք հաշիվ: Գրանցվեք այստեղ',
      'requiredField': 'Պարտադիր դաշտ',
      'invalidEmail': 'Մուտքագրեք ճիշտ էլ. հասցե',
      'shortPassword': 'Գաղտնաբառը պետք է լինի առնվազն 6 նիշ',
      'passwordMismatch': 'Գաղտնաբառերը չեն համընկնում',
      'registrationSuccess': 'Գրանցումը հաջողվեց։ Այժմ կարող եք մուտք գործել։',
      'cartTitle': 'Ձեր Զամբյուղը',
      'emptyCart': 'Ձեր զամբյուղը դատարկ է',
      'total': 'Ընդհանուր',
      'checkout': 'Ձևակերպել պատվերը',
      'orderSuccess': 'Պատվերը ընդունված է:',
      'orderMessage': 'Ձեր համեղ ուտեստը արդեն ճանապարհին է:',
      'addedToCart': 'Ավելացված է Ձեր Զամբյուղում',
      'next_step': 'Հաջորդ քայլը',
      'catAll': 'Ցանկ',
      'catPizza': 'Պիցցա',
      'catBurger': 'Բուրգեր',
      'catSushi': 'Սուշի',
      'catPasta': 'Պաստա',
      'catDessert': 'Աղանդեր',
      'catShaurma': 'Շաուրմա',
      'catBarbecue': 'Խորոված - Քյաբաբ',
      'catHotMeals': 'Տաք ուտեստներ',
      'catFastFood': 'Արագ սնունդ',
      'catCombo': 'Կոմբո',
      'catItalian': 'Իտալական',
      'catKorean': 'Կորեական',
      'catSandwiches': 'Սենդվիչներ',
      'catKFC': 'KFC',
      'phone': 'Հեռախոսահամար',
      'address': 'Տան հասցե',
      'paymentMethod': 'Վճարման եղանակ',
      'card': 'Քարտ',
      'cash': 'Կանխիկ',
      'cardNumber': 'Քարտի համար',
      'expiryDate': 'Գործողության ժամկետ',
      'cvv': 'CVV',
      'cashAmount': 'Որքա՞ն գումար ունեք',
      'changeNeeded': 'Մանրը',
      'confirmOrder': 'Հաստատել պատվերը',
      'insufficientCash': 'Գումարը պետք է լինի ընդհանուրից շատ',
      'fetchingLocation': 'Հասցեի որոնում...',
      'locationError': 'Չհաջողվեց ստանալ հասցեն',
      'locationPermissionDenied': 'Տեղորոշման թույլտվությունը մերժված է',
      'confirmLocation': 'Հաստատել հասցեն',
      'otherOptions': 'Այլ տարբերակներ',
      'alreadyHaveAccount': 'Արդեն ունե՞ք հաշիվ ։ Մուտք գործել',
      'emailAlreadyInUse': 'Այս էլ. հասցեն արդեն գրանցված է:',
      'phoneAlreadyInUse': 'Այս հեռախոսահամարը արդեն գրանցված է:',
      'usernameAlreadyInUse': 'Այս մուտքանունը արդեն զբաղված է:',
      'registerToPurchase': 'Գրանցվեք, որպեսզի կարողանաք գնումներ կատարել։',
      'home': 'Գլխավոր',
      'cart': 'Զամբյուղ',
      'profile': 'Պրոֆիլ',
      'personalAccount': 'Անձնական հաշիվ',
      'personalData': 'Անձնական տվյալներ',
      'orders': 'Պատվերներ',
      'settings': 'Կարգավորումներ',
      'activeOrders': 'Ակտիվ պատվերներ',
      'seeAll': 'Տեսնել բոլորը',
      'language': 'Լեզու',
      'paymentMethods': 'Վճարման եղանակներ',
      'logout': 'Դուրս գալ',
      'editProfile': 'Խմբագրել պրոֆիլը',
      'save': 'Պահպանել',
      'enter': 'Մուտքագրել',
      'cancel': 'Չեղարկել',
      'loginToSeeProfile': 'Մուտք գործեք պրոֆիլը տեսնելու համար',
      'portion': 'բաժին',
      'add': 'Ավելացնել',
      'backToHome': 'Վերադառնալ գլխավոր էջ',
      'editField': 'փոփոխում',
      'enterNew': 'Մուտքագրեք նոր',
      'onboarding1': 'Այստեղ յուրաքանչյուր ուտեստ պատմում է մի պատմություն:',
      'onboarding2': 'Պատրաստված է սրտով: Թխված սիրով:',
      'onboarding3': 'Ձեր սեղանը սպասում է:',
      'explore': 'Բացահայտել',
      'next': 'Հաջորդ',
      'start': 'Սկսել',
      'cardDetails': 'Քարտի տվյալները',
      'cardHolder': 'Քարտապանի անուն',
      'addCard': 'Ավելացնել քարտ',
      'idram': 'Իդրամ',
    },
    'en': {
      'appName': 'MASOOR',
      'searchHint': 'Search here, pick your favorite',
      'categoriesTitle': 'Menu',
      'popularRestaurants': 'Popular Restaurants',
      'noResults': 'No results found',
      'login': 'Login',
      'register': 'Register',
      'welcome': 'Welcome to MASOOR',
      'usernameOrEmail': 'Username or Email',
      'password': 'Password',
      'name': 'Full Name',
      'username': 'Username',
      'email': 'Email',
      'confirmPassword': 'Confirm Password',
      'noAccount': "Don't have an account? Register here",
      'requiredField': 'Required field',
      'invalidEmail': 'Enter a valid email',
      'shortPassword': 'Password must be at least 6 characters',
      'passwordMismatch': 'Passwords do not match',
      'registrationSuccess': 'Registration successful. You can now login.',
      'cartTitle': 'Your Cart',
      'emptyCart': 'Your cart is empty',
      'total': 'Total',
      'checkout': 'Checkout',
      'orderSuccess': 'Order Accepted!',
      'orderMessage': 'Your delicious meal is on its way!',
      'addedToCart': 'Added to your cart',
      'next_step': 'Next Step',
      'catAll': 'Menu',
      'catPizza': 'Pizza',
      'catBurger': 'Burger',
      'catSushi': 'Sushi',
      'catPasta': 'Pasta',
      'catDessert': 'Dessert',
      'catShaurma': 'Shaurma',
      'catBarbecue': 'Barbecue - Kebab',
      'catHotMeals': 'Hot Meals',
      'catFastFood': 'Fast Food',
      'catCombo': 'Combo',
      'catItalian': 'Italian',
      'catKorean': 'Korean',
      'catSandwiches': 'Sandwiches',
      'catKFC': 'KFC',
      'phone': 'Phone Number',
      'address': 'Home Address',
      'paymentMethod': 'Payment Method',
      'card': 'Card',
      'cash': 'Cash',
      'cardNumber': 'Card Number',
      'expiryDate': 'Expiry Date',
      'cvv': 'CVV',
      'cashAmount': 'How much money do you have?',
      'changeNeeded': 'Change',
      'confirmOrder': 'Confirm Order',
      'insufficientCash': 'Amount must be greater than total',
      'fetchingLocation': 'Fetching location...',
      'locationError': 'Could not get location',
      'locationPermissionDenied': 'Location permission denied',
      'confirmLocation': 'Confirm Location',
      'otherOptions': 'Other options',
      'alreadyHaveAccount': 'Already have an account? Login here',
      'emailAlreadyInUse': 'This email is already registered.',
      'phoneAlreadyInUse': 'This phone number is already registered.',
      'usernameAlreadyInUse': 'This username is already taken.',
      'registerToPurchase': 'Please register to be able to make purchases.',
      'home': 'Home',
      'cart': 'Cart',
      'profile': 'Profile',
      'personalAccount': 'Personal Account',
      'personalData': 'Personal Data',
      'orders': 'Orders',
      'settings': 'Settings',
      'activeOrders': 'Active Orders',
      'seeAll': 'See All',
      'language': 'Language',
      'paymentMethods': 'Payment Methods',
      'logout': 'Logout',
      'editProfile': 'Edit Profile',
      'save': 'Save',
      'enter': 'Enter',
      'cancel': 'Cancel',
      'loginToSeeProfile': 'Login to see profile',
      'portion': 'portion',
      'add': 'Add',
      'backToHome': 'Back to Home',
      'editField': 'Edit',
      'enterNew': 'Enter new',
      'onboarding1': 'Where every dish tells a story, and every guest leaves with one.',
      'onboarding2': 'Crafted with heart. Baked with fire.',
      'onboarding3': 'Your table is waiting.',
      'explore': 'Explore',
      'next': 'Next',
      'start': 'Start',
      'cardDetails': 'Card Details',
      'cardHolder': 'Name on Card',
      'addCard': 'Add Card',
      'idram': 'Idram',
    },
    'ru': {
      'appName': 'MASOOR',
      'searchHint': 'Ищите здесь, выбирайте любимое',
      'categoriesTitle': 'Меню',
      'popularRestaurants': 'Популярные рестораны',
      'noResults': 'Ничего не найдено',
      'login': 'Вход',
      'register': 'Регистрация',
      'welcome': 'Добро пожаловать в MASOOR',
      'usernameOrEmail': 'Имя пользователя или Email',
      'password': 'Пароль',
      'name': 'Имя Фамилия',
      'username': 'Имя пользователя',
      'email': 'Электронная почта',
      'confirmPassword': 'Подтвердите пароль',
      'noAccount': 'Нет аккаунта? Зарегистрируйтесь здесь',
      'requiredField': 'Обязательное поле',
      'invalidEmail': 'Введите корректный email',
      'shortPassword': 'Пароль должен быть не менее 6 символов',
      'passwordMismatch': 'Пароли не совпадают',
      'registrationSuccess': 'Регистрация прошла успешно. Теперь вы можете войти.',
      'cartTitle': 'Ваша корзина',
      'emptyCart': 'Ваша корзина пуста',
      'total': 'Итог',
      'checkout': 'Оформить заказ',
      'orderSuccess': 'Заказ принят!',
      'orderMessage': 'Ваша вкусная еда уже в пути!',
      'addedToCart': 'Добавлено в корзину',
      'next_step': 'Следующий шаг',
      'catAll': 'Все',
      'catPizza': 'Пицца',
      'catBurger': 'Бургер',
      'catSushi': 'Суши',
      'catPasta': 'Паста',
      'catDessert': 'Десерт',
      'catShaurma': 'Шаурма',
      'catBarbecue': 'Шашлык - Кебаб',
      'catHotMeals': 'Горячие блюда',
      'catFastFood': 'Фастфуд',
      'catCombo': 'Комбо',
      'catItalian': 'Итальянская',
      'catKorean': 'Корейская',
      'catSandwiches': 'Сэндвичи',
      'catKFC': 'KFC',
      'phone': 'Номер телефона',
      'address': 'Домашний адрес',
      'paymentMethod': 'Способ оплаты',
      'card': 'Карта',
      'cash': 'Наличные',
      'cardNumber': 'Номер карты',
      'expiryDate': 'Срок действия',
      'cvv': 'CVV',
      'cashAmount': 'Сколько у вас денег?',
      'changeNeeded': 'Сдача',
      'confirmOrder': 'Подтвердить заказ',
      'insufficientCash': 'Сумма должна быть больше итога',
      'fetchingLocation': 'Поиск адреса...',
      'locationError': 'Не удалось получить адрес',
      'locationPermissionDenied': 'Доступ к местоположению отклонен',
      'confirmLocation': 'Подтвердить местоположение',
      'otherOptions': 'Другие варианты',
      'alreadyHaveAccount': 'Уже есть аккаунт? Войти',
      'emailAlreadyInUse': 'Этот электронный адрес уже зарегистрирован.',
      'phoneAlreadyInUse': 'Этот номер телефона уже зарегистрирован.',
      'usernameAlreadyInUse': 'Это имя пользователя уже занято.',
      'registerToPurchase': 'Пожалуйста, зарегистрируйтесь, чтобы совершать покупки.',
      'home': 'Главная',
      'cart': 'Корзина',
      'profile': 'Профиль',
      'personalAccount': 'Личный кабинет',
      'personalData': 'Личные данные',
      'orders': 'Заказы',
      'settings': 'Настройки',
      'activeOrders': 'Активные заказы',
      'seeAll': 'Смотреть все',
      'language': 'Язык',
      'paymentMethods': 'Способы оплаты',
      'logout': 'Выйти',
      'editProfile': 'Редактировать профиль',
      'save': 'Сохранить',
      'enter': 'Ввести',
      'cancel': 'Отмена',
      'loginToSeeProfile': 'Войдите, чтобы увидеть профиль',
      'portion': 'порция',
      'add': 'Добавить',
      'backToHome': 'Вернуться на главную',
      'editField': 'Изменить',
      'enterNew': 'Введите новый',
      'onboarding1': 'Где каждое блюдо рассказывает историю, а каждый гость уходит с ней.',
      'onboarding2': 'Сделано с сердцем. Испечено с любовью.',
      'onboarding3': 'Ваш столик ждет.',
      'explore': 'Исследовать',
      'next': 'Далее',
      'start': 'Начать',
      'cardDetails': 'Данные карты',
      'cardHolder': 'Имя на карте',
      'addCard': 'Добавить карту',
      'idram': 'Идрам',
    },
  };

  void setLocale(Locale locale) async {
    if (!['hy', 'en', 'ru'].contains(locale.languageCode)) return;
    _currentLocale = locale;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_localeKey, locale.languageCode);
  }

  String translate(String key) {
    return _localizedValues[_currentLocale.languageCode]?[key] ?? key;
  }
}
